[package]

name = "multirost-rs"
version = "0.0.1"
authors = [ "Noah Juopperi <noahhju@googlemail.com>" ]

[dependencies]
clap = { version = "1.4.2", features = ["yaml"] }
regex = "0.1.41"
rand = "0.3.11"
hyper = "0.6.14"

[lib]
name = "multirost"

[[bin]]
name = "multirost-rs"
